# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[╭╴](#dde1e6 bold)$all\
[ ](bold #ff7eb6)
[╰─](#dde1e6 bold)$character"""

# Shows the username
[username]
style_user = 'bold #ff7eb6'
style_root = 'bold #ff7eb6'
format = '[\(](#dde1e6 bold)[$user]($style)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '@(#dde1e6 bold)[$hostname](bold #ff7eb6)[\)](#dde1e6 bold)'
disabled = false

[directory]
format = '[──](#dde1e6 bold)[\[](#dde1e6 bold)[$path](#33b1ff bold)[$read_only]($read_only_style)[\]](#dde1e6 bold) '

[character]
success_symbol = '[❯](bold #ff7eb6)'