return {
    -- {"Quote", '', '- Author'},
    {"Science works on the frontier between knowledge and ignorance.", '', '- Neil deGrasse Tyson'},
    {"Pain is information.", '', '- Some Dentist'},
    {"The true science of martial arts means practicing them in such a way that they will be useful at any time, and to teach them in such a way that they will be useful in all things.", '', '- Miyamoto Musashi'},
    {"Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", '', '- Miyamoto Musashi'},
    {"It's not about how hard you work until you tired, it's about how hard you work after you tired.", '', '- John Hammond'},
    {"A problem is an emotional state. Without emotions, it is just a situation.", '', ''},
    {"Focusing is the purposeful and deliberate alignment to a specific goal.", '', ''},
    {"Frustration passes, the experience we have gained through it remains.", '', ''},
    {"Dignity comes with pain. People who seek pleasure don't lead dignified lives.", '', '- Dr. K'},
    {"Be the resource you always wish you had.", '', ''},
    {"The best way to predict the future is to create it.", '', ''},
    {"Aller Anfang ist schwer. Anfangen ist einfach, Beharrlichkeit eine Kunst.", '', '- eps3.4_runtime-error.r00'},
    {"Take care of your pieces, and they will take care of you!", '', '- Some Chess Coach'},
    {"See how easily our technologies turn on us? The more power you think you have, the more quickly it slips from your grasp.", '', '- Deus Ex'},
    {"– How do you manage ADHD?", "– I don't. I manhandle it.", '- ThePrimeagen'},
    {"Question everything.", '', ''},
    -- {"", '', ''},
}
